# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Running Tests
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      id: test
      run: mvn clean test
    - name: Create Test Reports
      if: always() && (steps.test.outcome == 'failure')
      uses: actions/upload-artifact@v2
      with:
        name: "TestReport"
        path: "target/surefire-reports/*.xml"

  build:
    name: Compiling code
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - uses: actions/upload-artifact@v2
      with:
          name: "Absorb-Server"
          path: "target/*.jar"
          if-no-files-found: error
          
